name: Push Docker image to Docker Hub
runs-on: ubuntu-latest
needs: tests
steps:
  - name: Check out the repo
    uses: actions/checkout@v2 # Проверяет доступность репозитория DockerHub для workflow
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1 # Вызывает сборщик контейнеров docker
  - name: Login to Docker 
    uses: docker/login-action@v1 # Запуск скрипта авторизации на DockerHub
    with:
          username: ${{ secrets.DOCK_USER }}
          password: ${{ secrets.DOCK_PASS }}
  - name: Push to Docker Hub
    uses: docker/build-push-action@v2 # Выполняет push образа в DockerHub 
    with:
      push: true
      tags: 2498573548934587/infra_ac:latest
